name: The Development
description: A website about websites
url: http://the-development.github.io/thedevelopment/
dps_dir: http://the-development.github.io/thedevelopment/images/dps/
screenshots_dir: http://the-development.github.io/thedevelopment/images/screenshots/
markdown: redcarpet
highlighter: true
paginate: 8
paginate_path: "archives/:num"
exclude:
  - vendor
