name: The Development
description: A website about websites
url: http://thedevelopment.co
dps_dir: http://thedevelopment.co/images/dps/
screenshots_dir: http://thedevelopment.co/images/screenshots/
markdown: redcarpet
highlighter: true
paginate: 8
paginate_path: "archives/:num"
exclude:
  - vendor
